/*
 * File: app/store/CertType.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SignaTouch.store.CertType', {
    extend: 'Ext.data.Store',

    requires: [
        'SignaTouch.model.CertType'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            batchUpdateMode: 'complete',
            model: 'SignaTouch.model.CertType',
            storeId: 'CertType',
            data: [
                {
                    id: 'All',
                    des: 'All'
                },
                {
                    id: 'I',
                    des: 'Initial'
                },
                {
                    id: 'V',
                    des: 'Revision'
                },
                {
                    id: 'C',
                    des: 'Recert'
                }
            ]
        }, cfg)]);
    }
});