/*
 * File: app/store/MyArrayStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SignaTouch.store.MyArrayStore', {
    extend: 'Ext.data.Store',

    requires: [
        'SignaTouch.model.Gender'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            batchUpdateMode: 'complete',
            model: 'SignaTouch.model.Gender',
            storeId: 'MyArrayStore',
            data: [
                {
                    id: 'F',
                    des: 'Female'
                },
                {
                    id: 'M',
                    des: 'Male'
                }
            ]
        }, cfg)]);
    }
});