/*
 * File: app/store/SectionBQ3.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SignaTouch.store.SectionBQ3', {
    extend: 'Ext.data.Store',

    requires: [
        'SignaTouch.model.SectionBQ3'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            batchUpdateMode: 'complete',
            model: 'SignaTouch.model.SectionBQ3',
            storeId: 'SectionBQ3',
            data: [
                {
                    id: '1',
                    des: '1 - At Rest'
                },
                {
                    id: '2',
                    des: '2 - During Exercise'
                },
                {
                    id: '3',
                    des: '3 - During Sleep'
                }
            ]
        }, cfg)]);
    }
});