/*
 * File: app/store/SectionBQ2.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SignaTouch.store.SectionBQ2', {
    extend: 'Ext.data.Store',

    requires: [
        'SignaTouch.model.SectionBQ2'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            batchUpdateMode: 'complete',
            model: 'SignaTouch.model.SectionBQ2',
            storeId: 'SectionBQ2',
            data: [
                {
                    id: '1',
                    des: '1 - With patient in a chronic stable state as an outpatient'
                },
                {
                    id: '2',
                    des: '2 - Within 2 days prior to discharge from an inpatient facility to home'
                },
                {
                    id: '3',
                    des: '3 - under other circumstances'
                }
            ]
        }, cfg)]);
    }
});