/*
 * File: app/store/States.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SignaTouch.store.States', {
    extend: 'Ext.data.Store',

    requires: [
        'SignaTouch.model.state'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            batchUpdateMode: 'complete',
            model: 'SignaTouch.model.state',
            storeId: 'state',
            data: [
                {
                    id: 'Al',
                    des: 'Al'
                },
                {
                    id: 'AK',
                    des: 'AK'
                },
                {
                    id: 'AZ',
                    des: 'AZ'
                },
                {
                    id: 'AR',
                    des: 'AR'
                },
                {
                    id: 'CA',
                    des: 'CA'
                },
                {
                    id: 'CO',
                    des: 'CO'
                },
                {
                    id: 'CT',
                    des: 'CT'
                },
                {
                    id: 'DE',
                    des: 'DE'
                },
                {
                    id: 'FL',
                    des: 'FL'
                },
                {
                    id: 'GA',
                    des: 'GA'
                },
                {
                    id: 'HI',
                    des: 'HI'
                },
                {
                    id: 'ID',
                    des: 'ID'
                },
                {
                    id: 'IL',
                    des: 'IL'
                },
                {
                    id: 'IN',
                    des: 'IN'
                },
                {
                    id: 'IA',
                    des: 'IA'
                },
                {
                    id: 'KS',
                    des: 'KS'
                },
                {
                    id: 'KY',
                    des: 'KY'
                },
                {
                    id: 'LA',
                    des: 'LA'
                },
                {
                    id: 'ME',
                    des: 'ME'
                },
                {
                    id: 'MD',
                    des: 'MD'
                },
                {
                    id: 'MA',
                    des: 'MA'
                },
                {
                    id: 'MI',
                    des: 'MI'
                },
                {
                    id: 'MN',
                    des: 'MN'
                },
                {
                    id: 'MS',
                    des: 'MS'
                },
                {
                    id: 'MO',
                    des: 'MO'
                },
                {
                    id: 'MT',
                    des: 'MT'
                },
                {
                    id: 'NE',
                    des: 'NE'
                },
                {
                    id: 'NV',
                    des: 'NV'
                },
                {
                    id: 'NH',
                    des: 'NH'
                },
                {
                    id: 'NJ',
                    des: 'NJ'
                },
                {
                    id: 'NM',
                    des: 'NM'
                },
                {
                    id: 'NY',
                    des: 'NY'
                },
                {
                    id: 'NC',
                    des: 'NC'
                },
                {
                    id: 'ND',
                    des: 'ND'
                },
                {
                    id: 'OH',
                    des: 'OH'
                },
                {
                    id: 'OK',
                    des: 'OK'
                },
                {
                    id: 'OR',
                    des: 'OR'
                },
                {
                    id: 'PA',
                    des: 'PA'
                },
                {
                    id: 'RI',
                    des: 'RI'
                },
                {
                    id: 'SC',
                    des: 'SC'
                },
                {
                    id: 'SD',
                    des: 'SD'
                },
                {
                    id: 'TN',
                    des: 'TN'
                },
                {
                    id: 'TX',
                    des: 'TX'
                },
                {
                    id: 'UT',
                    des: 'UT'
                },
                {
                    id: 'VT',
                    des: 'VT'
                },
                {
                    id: 'VA',
                    des: 'VA'
                },
                {
                    id: 'WA',
                    des: 'WA'
                },
                {
                    id: 'WV',
                    des: 'WV'
                },
                {
                    id: 'WI',
                    des: 'WI'
                },
                {
                    id: 'WY',
                    des: 'WY'
                }
            ]
        }, cfg)]);
    }
});