/*
 * File: app/view/AddDomain.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SignaTouch.view.AddDomain', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    id: 'AddDomainID',
    style: 'margin: 0 auto;\r\n    text-align: left;\r\n    width: 650px;',
    bodyPadding: '50 0 50 0',
    bodyStyle: 'background-color:#3892d3;',
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    id: 'DomainForm',
                    layout: 'auto',
                    bodyPadding: 10,
                    bodyStyle: 'background-color:#a5cfff;',
                    title: '',
                    titleAlign: 'center',
                    items: [
                        {
                            xtype: 'container',
                            id: 'AddUserBreadcrumb3',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    id: 'BreadcrumbAddUser3',
                                    fieldLabel: '<b>Add New Domain</b>',
                                    labelSeparator: '&nbsp;',
                                    labelWidth: 180
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            style: 'border-style:solid;\r\nborder-color:#000000;',
                            title: '<font size="4">New Domain</font>',
                            items: [
                                {
                                    xtype: 'container',
                                    id: 'Password7',
                                    margin: '7 0 7 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'txtDomainNameID',
                                            itemId: '',
                                            width: 300,
                                            fieldLabel: '<b>Domain Name&nbsp;<span style="color:#D94E37;">*</span><b/>',
                                            labelWidth: 150,
                                            fieldStyle: 'text-transform:capitalize',
                                            inputId: 'txtDomainName',
                                            allowBlank: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    id: 'Password8',
                                    margin: '7 0 7 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'txtDefaultCOSID',
                                            itemId: '',
                                            width: 300,
                                            fieldLabel: '<b>Default COS&nbsp;<span style="color:#D94E37;">*</span><b/>',
                                            labelWidth: 150,
                                            fieldStyle: 'text-transform:capitalize',
                                            inputId: 'txtDefaultCOS',
                                            allowBlank: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    id: 'Password9',
                                    margin: '7 0 7 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'txtDescriptionID',
                                            itemId: '',
                                            width: 300,
                                            fieldLabel: '<b>Descriptions&nbsp;<b/>',
                                            labelWidth: 150,
                                            fieldStyle: 'text-transform:capitalize',
                                            inputId: 'txtDescription'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    itemId: 'Button',
                                    margin: '7 0 7 0',
                                    maxWidth: 600,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            formBind: true,
                                            id: 'btnCreate3',
                                            margin: '0 10 0 0',
                                            padding: '',
                                            width: 92,
                                            text: 'Save',
                                            listeners: {
                                                click: {
                                                    fn: me.onBtnCreate2Click1,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            formBind: false,
                                            id: 'btnReset3',
                                            margin: '0 0 0 0',
                                            width: 92,
                                            text: 'Reset',
                                            listeners: {
                                                click: {
                                                    fn: me.onBtnReset2Click1,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    id: 'HiddenID2',
                                    fieldLabel: 'Label',
                                    inputId: 'HiddenInputID'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onBtnCreate2Click1: function(button, e, eOpts) {
        var form =  Ext.getCmp('COSForm');  // Login form
        //var userName =  Ext.getCmp('LBLUsername');
        //var header = button.up('headerPanel');
        values = form.getValues();    // Form values


        // Success
        var successCallback = function(resp, ops) {
            console.log(resp.responseText);
            if(resp.responseText === 'true'){

                Ext.Msg.alert("New COS created", 'New COS is created successfully');
                Ext.getCmp('txtCOSNameID').reset();
                Ext.getCmp('txtCOSdescriptionID').reset();
                Ext.getCmp('txtCOSNotesID').reset();
            }
            else if(resp.responseText === 'false'){
                Ext.Msg.alert("This COS already exists", 'This COS already exists');

            }
            else {
                    Ext.Msg.alert("New COS cannot be created", 'New COS cannot be created');
                }



        };

        // Failure
        var failureCallback = function(resp, ops) {


            // Show login failure error
            //Ext.Msg.alert("Login Failure", 'Incorrect Username or Password');

        };
        //adding loader
        Ext.Ajax.on('beforerequest', function(){

            var pnl=Ext.getCmp('AddCOSID');
            pnl.setLoading(true, true);
        });


        Ext.Ajax.on('requestcomplete', function(){

            Ext.getCmp('AddCOSID').setLoading(false,false);
        });
        var username = localStorage.getItem("email");

        // TODO: Login using server-side authentication service
        Ext.Ajax.request({url: "services/CreateAccount.php?action=ZimbraCreateCOS&user="+username,
                          method: 'POST',
                          params: values,
                          success: successCallback,
                          failure: failureCallback
                         });
    },

    onBtnReset2Click1: function(button, e, eOpts) {
        Ext.getCmp('COSForm').getForm().reset();
    }

});